# Generated by Django 5.0.6 on 2024-07-04 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCompras',
            fields=[
                ('reporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.reporte')),
                ('total_ventas', models.FloatField()),
                ('ventas', models.ManyToManyField(to='inventario.compra')),
            ],
            bases=('inventario.reporte',),
        ),
        migrations.CreateModel(
            name='ReporteVentas',
            fields=[
                ('reporte_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventario.reporte')),
                ('total_ventas', models.FloatField()),
                ('ventas', models.ManyToManyField(to='inventario.venta')),
            ],
            bases=('inventario.reporte',),
        ),
    ]
